"use client";
import {useEffect,useRef,useState} from "react";
import {readOfflineResponse,saveOfflinePack} from "../lib/offline-pack";
export function OfflinePackControl({id,revision}:{id:string;revision:string|null}){
 const [rights,setRights]=useState(false),[days,setDays]=useState(7),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");const active=useRef<AbortController|null>(null);
 useEffect(()=>()=>active.current?.abort(),[]);
 async function prepare(){if(!rights||!revision||busy)return;const controller=new AbortController();active.current=controller;setBusy(true);setNotice("");const timeout=setTimeout(()=>controller.abort(),15000);
  try{const pack=await readOfflineResponse(await fetch(`/api/song/${encodeURIComponent(id)}/offline-pack`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({revision,rightsConfirmed:true,days}),signal:controller.signal,cache:"no-store"}));
   if(!("serviceWorker" in navigator))throw Error("Offline opening is unavailable in this browser.");const registration=await navigator.serviceWorker.register("/offline/sw.js",{scope:"/offline/"});
   if(!registration.active)await new Promise<void>((resolve,reject)=>{const worker=registration.installing??registration.waiting;if(!worker)return reject(Error("Offline shell unavailable."));const changed=()=>{if(worker.state==="activated"){worker.removeEventListener("statechange",changed);resolve();}else if(worker.state==="redundant"){worker.removeEventListener("statechange",changed);reject(Error("Offline shell could not be saved."));}};worker.addEventListener("statechange",changed);controller.signal.addEventListener("abort",()=>{worker.removeEventListener("statechange",changed);reject(Error("Offline preparation timed out."));},{once:true});changed();});
   controller.signal.throwIfAborted();await saveOfflinePack(pack);setNotice("Selected Original saved. Open the offline player once before disconnecting.");
  }catch(error){setNotice(error instanceof Error?error.message:"Offline preparation failed. Previous pack retained.");}finally{clearTimeout(timeout);if(active.current===controller){active.current=null;setBusy(false);}}
 }
 return <details className="my-3 border rounded-xl p-3 text-sm" aria-label="Private offline pack"><summary className="min-h-11 cursor-pointer">Optional offline practice pack</summary><p>Save this stored Original and its MIDI/notation files on this browser only. One pack, at most 8 MiB and four minutes; synth sound and note-letter practice. It replaces the previous pack. Other songs require a network connection.</p><p>People with access to this browser can read local music. The screen lock is not encryption or an identity check. Expiry follows this device’s clock. Removing the pack cannot revoke downloaded copies.</p><fieldset disabled={busy}><label className="block"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/> I have permission to keep this arrangement for private offline use on this device.</label><label className="block">Offline expiry <select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>1 day</option><option value={7}>7 days</option><option value={30}>30 days</option></select></label><button className="min-h-11 underline" disabled={!rights||!revision} onClick={()=>void prepare()}>Save selected Original offline</button></fieldset>{!revision&&<p>A pinned publication is required; reload or use a reviewed import.</p>}<p role="status">{notice}</p><a className="min-h-11 inline-block underline" href="/offline/index.html">Open offline player</a></details>;
}
