"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
export function OwnerDeletion({baseId,revision,disabled=false}:{baseId:string;revision:string|null;disabled?:boolean}){
 const [preview,setPreview]=useState<{baseId:string;title:string;publicationRevision:string;bytes:number}|null>(null),[days,setDays]=useState(14),[accepted,setAccepted]=useState(false),[confirmation,setConfirmation]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
 const controllerRef=useRef<AbortController|null>(null);useEffect(()=>()=>controllerRef.current?.abort(),[]);
 async function run(commit=false){if(busy||disabled||!revision)return;const controller=new AbortController();controllerRef.current=controller;setBusy(true);setNotice("");const timer=setTimeout(()=>controller.abort(),30000);
  try{const response=await fetch(commit?"/api/catalog/tombstones":`/api/catalog/tombstones?baseId=${encodeURIComponent(baseId)}`,{signal:controller.signal,...(commit?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"quarantine",baseId,confirmBaseId:confirmation,expectedRevision:preview?.publicationRevision,retentionDays:days,policyAccepted:accepted})}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Quarantine unavailable.");if(controller.signal.aborted)return;
   if(commit){setDone(true);setNotice(`Lesson hidden. Undo is available until ${new Date(result.receipt.expiresAt).toLocaleString()}.`);}else{if(result.preview.publicationRevision!==revision)throw new Error("This version changed. Reload before reviewing deletion.");setPreview(result.preview);setAccepted(false);setConfirmation("");}
  }catch(error){if(controllerRef.current===controller)setNotice(controller.signal.aborted?"Request interrupted. Open maintenance to check the durable tombstone before retrying.":error instanceof Error?error.message:"Quarantine unavailable.");}
  finally{clearTimeout(timer);if(controllerRef.current===controller)setBusy(false);}
 }
 return <details className="my-3 border rounded p-3 text-sm" aria-label="Reversible lesson deletion"><summary className="min-h-11">Remove owner lesson</summary><p>This hides every variant and retains its owned source and artifacts for undo. It does not delete practice history or unrelated files.</p>
 <fieldset disabled={busy||disabled||done} className="space-y-2"><button className="min-h-11 underline" disabled={!revision} onClick={()=>void run()}>Preview quarantine</button>{!revision&&<p>A current publication pin is required before reversible deletion.</p>}
 {preview&&<div aria-label="Quarantine preview"><p>{preview.title} · {baseId} · {(preview.bytes/1048576).toFixed(2)} MiB</p><p className="break-all">Reviewed version: {preview.publicationRevision}</p><label>Undo retention<select aria-label="Undo retention" className="min-h-11 border rounded mx-2" value={days} onChange={event=>{setDays(Number(event.target.value));setAccepted(false);}}>{[7,14,30].map(value=><option key={value} value={value}>{value} days</option>)}</select></label><p>Maximum 128 MiB per lesson, 20 retained lessons and 512 MiB total. Expiry disables undo; files remain until an explicit purge.</p><label className="block"><input type="checkbox" checked={accepted} onChange={event=>setAccepted(event.target.checked)}/> I choose this local quarantine and retention policy.</label><label className="block">Confirm lesson base ID<input className="min-h-11 block border rounded px-2 w-full" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label><button className="min-h-11 border rounded px-3" disabled={!accepted||confirmation!==baseId} onClick={()=>void run(true)}>Quarantine reviewed lesson</button><button className="min-h-11 underline ml-3" onClick={()=>{setPreview(null);setAccepted(false);setConfirmation("");}}>Discard deletion preview</button></div>}</fieldset>
 {notice&&<p role="status">{notice}</p>}{(done||notice)&&<Link className="min-h-11 inline-flex items-center underline" href="/maintenance">Open quarantine maintenance</Link>}
 </details>;
}
