"use client";
import {useEffect,useRef,useState} from "react";
import type {Note} from "@keyspilli/midi";
import type {AudioEngine} from "@keyspilli/player-core";
import type {buildHarmonyCandidate} from "@/lib/harmony-candidate";
type Candidate=ReturnType<typeof buildHarmonyCandidate>;
type Source={id:string;baseId:string;title:string;sourceFingerprint:string;publicationRevision:string;tempoBpm:number;key:string;durationBeats:number;notes:Note[]};
export function OwnerHarmony({songId,revision}:{songId:string;revision:string}){
 const [source,setSource]=useState<Source|null>(null),[draft,setDraft]=useState('[{"kind":"chord","beat":0,"durationBeats":1,"name":"C"}]'),[candidate,setCandidate]=useState<Candidate|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const active=useRef<AbortController|null>(null),audio=useRef<AudioEngine|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),mounted=useRef(true),audioGeneration=useRef(0);
 function stop(){audioGeneration.current++;if(timer.current)clearTimeout(timer.current);timer.current=null;audio.current?.cancelAll();}
 useEffect(()=>{mounted.current=true;const interrupt=()=>stop();window.addEventListener('blur',interrupt);document.addEventListener('visibilitychange',interrupt);return()=>{mounted.current=false;active.current?.abort();stop();audio.current?.dispose();window.removeEventListener('blur',interrupt);document.removeEventListener('visibilitychange',interrupt);};},[]);
 async function request(preview=false){if(busy)return;stop();const controller=new AbortController();active.current=controller;setBusy(true);setNotice("");const deadline=setTimeout(()=>controller.abort(),30000);
  try{let events:unknown;if(preview){if(draft.length>32000)throw new Error("Draft exceeds 32 KiB.");events=JSON.parse(draft);}
   const response=await fetch(preview?'/api/catalog/harmony':`/api/catalog/harmony?id=${encodeURIComponent(songId)}&revision=${encodeURIComponent(revision)}`,{signal:controller.signal,...(preview?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:songId,revision,sourceFingerprint:source?.sourceFingerprint,events})}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Preview unavailable.");if(controller.signal.aborted||!mounted.current)return;if(preview)setCandidate(result);else{setSource(result);setCandidate(null);}}
  catch(error){if(active.current===controller&&mounted.current){setCandidate(null);setNotice(controller.signal.aborted?"Preview timed out; reload before reviewing another version.":error instanceof Error?error.message:"Preview unavailable.");}}
  finally{clearTimeout(deadline);if(active.current===controller&&mounted.current)setBusy(false);}
 }
 async function hear(notes:Note[]){if(!source)return;stop();const generation=audioGeneration.current;const start=candidate?.timeline.chords[0]?.beat??0,secondsPerBeat=60/source.tempoBpm,end=Math.min(source.durationBeats,start+8/secondsPerBeat);
  const audible=notes.flatMap(note=>{const from=Math.max(start,note.start),to=Math.min(end,note.start+note.dur);return to>from?[{midi:note.midi,startSec:(from-start)*secondsPerBeat,durSec:(to-from)*secondsPerBeat,vel:note.vel,hand:note.hand}]:[];});
  if(audible.length>512){setNotice("This short audition exceeds 512 sounding notes. Choose a smaller draft passage.");return;}
  try{if(!audio.current){const {AudioEngine}=await import('@keyspilli/player-core');if(!mounted.current||generation!==audioGeneration.current)return;audio.current??=new AudioEngine();audio.current.sustainPedal=false;}
   const context=audio.current.ensure();await context.resume();if(!mounted.current||generation!==audioGeneration.current)return;for(const note of audible)audio.current.noteOn(note,note.startSec);timer.current=setTimeout(()=>stop(),Math.max(100,(end-start)*secondsPerBeat*1000+100));setNotice(`Plain synth preview, original tempo/key; at most 8 seconds. ${audible.length} notes. Listening and keyboard review remain pending.`);
  }catch{stop();setNotice("Audio preview unavailable. Symbolic draft downloads remain available.");}
 }
 function download(kind:"timeline"|"midi"|"xml") {if(!candidate)return;const value=kind==="timeline"?JSON.stringify(candidate.timeline,null,2):kind==="xml"?candidate.xml:Uint8Array.from(atob(candidate.midi),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([value],{type:kind==="timeline"?'application/json':kind==="xml"?'application/xml':'audio/midi'})),link=document.createElement('a');link.href=url;link.download=`${songId}-unreviewed-${candidate.digest.slice(0,12)}.${kind==="timeline"?'json':kind==='xml'?'musicxml':'mid'}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section aria-label="Owner harmony preview" className="space-y-4"><p>Preview a bounded harmony draft against unchanged Original. This editor uses quarter-beat steps (sixteenth notes). Rest (N.C.) and unknown (?) remain distinct; unsupported symbols are display-only. Candidate events stay unreviewed.</p>
 <button disabled={busy} className="min-h-11 border rounded px-3" onClick={()=>void request()}>Load pinned Original</button>
 {source&&<><h2 className="text-lg font-semibold">{source.title}</h2><p>{source.key} · {source.tempoBpm} BPM · {source.durationBeats} beats</p><p className="text-xs break-all">Version {source.publicationRevision}<br/>Source/output {source.sourceFingerprint}</p><label className="block">Harmony event draft<textarea aria-label="Harmony event draft" className="block w-full min-h-40 font-mono text-sm border rounded p-2" maxLength={32000} value={draft} disabled={busy} onChange={event=>{stop();setDraft(event.target.value);setCandidate(null);}}/></label><p>Each event has kind (chord/rest/unknown), beat and durationBeats. Chords also have name and optional notes (up to ten supported voicing pitches). At most 256 events; spans cannot overlap. Omitted regions have no draft harmony.</p><button disabled={busy} className="min-h-11 border rounded px-3" onClick={()=>void request(true)}>Validate harmony preview</button><button disabled={busy} className="min-h-11 underline ml-3" onClick={()=>{stop();setCandidate(null);setNotice('Draft discarded. Accepted music unchanged.');}}>Discard harmony draft</button></>}
 {candidate&&<div className="border rounded p-3 space-y-2" aria-label="Unreviewed harmony candidate"><h3>Normalized candidate · admission unavailable</h3><p className="text-xs break-all">{candidate.digest}</p>{candidate.timeline.chords.map((chord,i)=><p key={i}>{chord.beat}–{chord.beat+chord.durationBeats}: {chord.name} · {chord.notes?.length?chord.notes.join(', '):'silent / display-only'} · source unknown</p>)}{candidate.warnings.map((warning,i)=><p key={i}>{warning}</p>)}
 <div className="flex flex-wrap gap-3"><button className="min-h-11 underline" onClick={()=>void hear(source!.notes)}>Hear unchanged Original</button><button className="min-h-11 underline" onClick={()=>void hear(candidate.notes)}>Hear harmony candidate</button><button className="min-h-11 underline" onClick={stop}>Stop preview</button><button className="min-h-11 underline" onClick={()=>download('timeline')}>Save candidate sidecar</button><button className="min-h-11 underline" onClick={()=>download('midi')}>Download candidate MIDI</button><button className="min-h-11 underline" onClick={()=>download('xml')}>Download candidate MusicXML</button></div>
 <p>The version-bound admission importer is unavailable in this checkout. Preparation, listening, keyboard evidence and atomic publication are required before replacing accepted backing. These downloads do not approve or publish the candidate.</p><button disabled className="min-h-11 border rounded px-3">Publication unavailable</button></div>}
 {notice&&<p role="status">{notice}</p>}
 </section>;
}
