import { describe, expect, it } from 'vitest';
import { createHash } from 'node:crypto';
import { parsePairedPlayerCapture, parsePlayerInputEvidence, validatePlayerSignalBytes } from '../src/player-input-evidence.js';
const hash='a'.repeat(64);
const pin=(encoding='pcm-f32le',channels=2)=>({path:'/fixture.wav',sha256:hash,encoding,sampleRate:44100,channels,frames:128});
const capture=()=>({schemaVersion:1,kind:'keyspilli-player-paired-capture',id:'control',input:pin(),forwardOutput:pin("pcm-f32le",1),output:pin('pcm-s16le',1),firstSampleContextSeconds:1,renderer:{moduleVersion:'1.0.0',moduleSha256:hash,browserVersion:'151.0'},compressor:{threshold:-24,knee:12,ratio:3,attack:.005,release:.15},sampleAssetPins:[{url:'https://fixture.invalid/sample',sha256:hash,bytes:1024}]});
const receipt=()=>({schemaVersion:1,kind:'keyspilli-player-input-evidence',captureSha256:hash,inputSha256:hash,analyzerSha256:hash,referenceBankSha256:hash,fitInterval:{startSeconds:0,endSeconds:1.2},status:'matched',historyPitchCandidates:[60,64,67],rawResidual:.01,currentPitchSetEstimate:null,completeness:'unknown',audibility:'not-established',resources:{elapsedSeconds:1,peakRssBytes:1024},limitations:['Provenance labels are assertions; not authenticated acoustic truth.']});
function wav(float:boolean){const channels=float?2:1, width=float?4:2,b=Buffer.alloc(44+128*channels*width);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(float?3:1,20);b.writeUInt16LE(channels,22);b.writeUInt32LE(44100,24);b.writeUInt32LE(44100*channels*width,28);b.writeUInt16LE(channels*width,32);b.writeUInt16LE(width*8,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);if(float)b.writeFloatLE(1.5,44);return b;}
describe('paired signal boundaries',()=>{
 it('rejects_mismatched_signal_frames_or_clock',()=>{const x=capture();x.output.frames++;expect(()=>parsePairedPlayerCapture(x)).toThrow(/frames/);x.output.frames--;x.firstSampleContextSeconds=NaN;expect(()=>parsePairedPlayerCapture(x)).toThrow(/clock/);});
 it('rejects_nonfinite_profile',()=>{const x=capture();x.compressor.ratio=NaN;expect(()=>parsePairedPlayerCapture(x)).toThrow(/compressor/);});
 it('does_not_convert_output_to_input_provenance',()=>{const x=capture();x.input.encoding='pcm-s16le';expect(()=>parsePairedPlayerCapture(x)).toThrow(/input/);});
 it('preserves_input_above_unity',()=>{const b=wav(true),p={...pin(),sha256:createHash('sha256').update(b).digest('hex')};validatePlayerSignalBytes(p,b);expect(b.readFloatLE(44)).toBe(1.5);b.writeFloatLE(Infinity,44);p.sha256=createHash('sha256').update(b).digest('hex');expect(()=>validatePlayerSignalBytes(p,b)).toThrow(/nonfinite/);});
 it('legacy_capture_remains_mono_pcm16',()=>{const b=wav(false);validatePlayerSignalBytes({...pin('pcm-s16le',1),sha256:createHash('sha256').update(b).digest('hex')},b);expect(b.readUInt16LE(20)).toBe(1);expect(b.readUInt16LE(22)).toBe(1);});
 it('rejects stale bytes and false frame pins',()=>{const b=wav(true);expect(()=>validatePlayerSignalBytes(pin(),b)).toThrow(/hash/);const p={...pin(),sha256:createHash('sha256').update(b).digest('hex'),frames:129};expect(()=>validatePlayerSignalBytes(p,b)).toThrow(/frames/);});
 it('withholds invalid acceptance claims and quiet subsets',()=>{expect(parsePlayerInputEvidence(receipt()).historyPitchCandidates).toEqual([60,64,67]);for(const bad of [{completeness:'complete'},{currentPitchSetEstimate:[60]},{audibility:'established'},{status:'uncertain'},{rawResidual:.06},{historyPitchCandidates:[60,60]}])expect(()=>parsePlayerInputEvidence({...receipt(),...bad})).toThrow();});
 it('rejects out-of-scope history and unbounded resources',()=>{for(const bad of [{fitInterval:{startSeconds:0,endSeconds:2}},{resources:{elapsedSeconds:NaN,peakRssBytes:1}},{resources:{elapsedSeconds:1,peakRssBytes:3*1024**3}}])expect(()=>parsePlayerInputEvidence({...receipt(),...bad})).toThrow();});
});
