import {parseMidi} from '../../../packages/midi/src/parse';
import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
const headers={Authorization:'Bearer test-token-for-e2e','Content-Type':'application/xml'};
test('an opted-in MIDI take captures physical intervals and pedal, replays without grading, and keeps interrupted raw events',async({page,request})=>{
 const xml='<score-partwise><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1">'+Array.from({length:4},(_,i)=>`<measure number="${i+1}">${i===0?'<attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes>':''}${['C','D','E','G'].map(step=>`<note><pitch><step>${step}</step><octave>4</octave></pitch><duration>1</duration><type>quarter</type></note>`).join('')}</measure>`).join('')+'</part></score-partwise>';
 const response=await request.post('/api/uploads?title=MIDI%20Take%20Fixture&artist=Fixture',{headers,data:Buffer.from(xml)});expect(response.ok(),await response.text()).toBe(true);const receipt=await response.json(),id=receipt.songIds.find((v:string)=>v.endsWith('-a')),path=join(process.env.KEYSPILLI_E2E_SCRATCH_DIR!,'artifacts',receipt.baseId,'a','notes.json'),before=await readFile(path);
 try{
  await page.addInitScript(()=>{
   localStorage.setItem('keyspilli.prefs.v1',JSON.stringify({soundSource:'synth',backgroundMode:'piano',transpose:0}));
   const input={id:'take-device',name:'Controlled take MIDI',state:'connected',onmidimessage:null as ((event:{data:Uint8Array;timeStamp:number})=>void)|null},access={inputs:new Map([[input.id,input]]),onstatechange:null as (()=>void)|null};
   Object.defineProperty(navigator,'requestMIDIAccess',{value:async()=>access,configurable:true});
   (window as unknown as {__takeMessage:(status:number,pitch:number,value:number)=>void}).__takeMessage=(status,pitch,value)=>input.onmidimessage?.({data:new Uint8Array([status,pitch,value]),timeStamp:performance.now()});
   (window as unknown as {__takeUnplug:()=>void}).__takeUnplug=()=>{access.inputs.clear();access.onstatechange?.();};
  });
  await page.goto(`/player/${id}/beginner`);const history=await page.evaluate(()=>localStorage.getItem('keyspilli.practice.v1'));
  await page.getByRole('button',{name:'Input',exact:true}).click();await page.getByRole('button',{name:'Connect MIDI',exact:true}).click();await page.getByRole('combobox',{name:'MIDI device',exact:true}).selectOption('take-device');await page.getByRole('combobox',{name:'MIDI channel',exact:true}).selectOption('0');await page.getByRole('button',{name:'Close tools'}).click();
  const panel=page.getByLabel('Local MIDI practice take');await panel.locator('summary').click();await panel.getByRole('checkbox',{name:'I want to record this private local performance.'}).check();await panel.getByRole('button',{name:'Record MIDI take',exact:true}).click();await expect(panel.getByLabel('MIDI take status')).toContainText('Get ready');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Practice',exact:true})).toBeDisabled();const deletion=page.getByLabel('Reversible lesson deletion');await deletion.locator('summary').click();await expect(deletion.getByRole('button',{name:'Preview quarantine'})).toBeDisabled();const rhythm=page.getByLabel('Rhythm-only passage coach');await rhythm.locator('summary').click();await expect(rhythm.getByRole('button',{name:'Start rhythm-only attempt'})).toBeDisabled();await page.waitForTimeout(1100);
  await page.evaluate(async()=>{const send=(window as unknown as {__takeMessage:(status:number,pitch:number,value:number)=>void}).__takeMessage;send(0x90,60,37);await new Promise(r=>setTimeout(r,50));send(0xb0,64,127);send(0x80,60,0);await new Promise(r=>setTimeout(r,50));send(0x90,60,100);await new Promise(r=>setTimeout(r,50));send(0x80,60,0);send(0xb0,64,0);});await panel.getByRole('button',{name:'Stop MIDI take',exact:true}).click();await expect(rhythm.getByRole('button',{name:'Start rhythm-only attempt'})).toBeEnabled();await expect(panel).toContainText('6 raw events');await expect(panel).toContainText('2 key intervals');
  const download=async()=>{const event=page.waitForEvent('download');await panel.getByRole('button',{name:'Download raw MIDI take'}).click();const file=await(await event).path();return JSON.parse(await readFile(file!,'utf8'));};const raw=await download();expect(raw.kind).toBe('owner-midi-performance');expect(raw.context.target.fingerprint).toMatch(/^sha256:[a-f0-9]{64}$/);expect(raw.events.map((e:{kind:string;value:number})=>[e.kind,e.value])).toEqual([['on',37],['pedal',127],['off',0],['on',100],['off',0],['pedal',0]]);
  const midiEvent=page.waitForEvent('download');await panel.getByRole('button',{name:'Download performance MIDI'}).click();const midiPath=await(await midiEvent).path(),midiBytes=await readFile(midiPath!);expect(midiBytes.toString('hex')).toContain('b0407f');expect(midiBytes.toString('hex')).toContain('b04000');const parsed=parseMidi(midiBytes);expect(parsed.notes.map(n=>n.vel)).toEqual([37,100]);expect(parsed.notes[0]!.start/2).toBeCloseTo(raw.events[0].sec,2);expect(parsed.notes[0]!.dur/2).toBeCloseTo(raw.events[2].sec-raw.events[0].sec,2);
  await panel.getByLabel('Take seek (seconds)').fill('0.05');await panel.getByLabel('Take replay speed').selectOption('2');await panel.getByRole('button',{name:'Hear performed take'}).click();await expect(panel.getByLabel('MIDI take status')).toContainText('Replaying');await page.evaluate(()=>(window as unknown as {__takeMessage:(status:number,pitch:number,value:number)=>void}).__takeMessage(0x90,67,80));await expect(panel.getByRole('button',{name:'Download raw MIDI take'})).toBeEnabled();expect((await download()).events).toEqual(raw.events);
  await panel.getByRole('button',{name:'Record MIDI take',exact:true}).click();await page.waitForTimeout(1100);await page.evaluate(()=>{const w=window as unknown as {__takeMessage:(s:number,p:number,v:number)=>void;__takeUnplug:()=>void};w.__takeMessage(0x90,64,90);w.__takeMessage(0xb0,64,127);w.__takeUnplug();});await expect(panel.getByLabel('MIDI take status')).toContainText('interrupted');const interrupted=await download();expect(interrupted.status).toBe('interrupted');expect(interrupted.events.map((e:{kind:string})=>e.kind)).toEqual(['on','pedal']);
  expect(await readFile(path)).toEqual(before);expect(await page.evaluate(()=>localStorage.getItem('keyspilli.practice.v1'))).toBe(history);await panel.getByRole('button',{name:'Remove MIDI take'}).click();await expect(panel.getByRole('button',{name:'Download raw MIDI take'})).toHaveCount(0);
 }finally{expect((await request.delete(`/api/songs/${receipt.baseId}`,{headers})).ok()).toBe(true);}
});
