import {test,expect} from "@playwright/test";
import {readFile} from "node:fs/promises";
import {join} from "node:path";
import {normalizeChordTimeline} from "../../../packages/catalog/src/chord-timeline";
const xml=`<score-partwise><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes>${['C','D','E','F','G','A','B','C'].map(step=>`<note><pitch><step>${step}</step><octave>4</octave></pitch><duration>1</duration></note>`).join('')}</measure></part></score-partwise>`;
test("owner harmony preview exports an unreviewed sidecar without changing accepted music and refuses a stale version",async({page,request})=>{
 const headers={Authorization:"Bearer test-token-for-e2e","Content-Type":"application/xml"},created=await request.post('/api/uploads?title=Harmony%20Fixture&artist=Author',{headers,data:Buffer.from(xml)});expect(created.ok(),await created.text()).toBe(true);
 const receipt=await created.json(),id=receipt.songIds.find((id:string)=>id.endsWith('-a')),path=join(process.env.KEYSPILLI_E2E_SCRATCH_DIR!,'artifacts',receipt.baseId,'a','notes.json'),original=await readFile(path);
 try{
  expect((await request.get(`/api/catalog/harmony?id=${id}&revision=${receipt.publicationRevision}`)).status()).toBe(401);
  await page.goto(`/maintenance/harmony?id=${id}&revision=${receipt.publicationRevision}`);await page.getByRole('button',{name:'Load pinned Original'}).click();await expect(page.getByRole('heading',{name:'Harmony Fixture'})).toBeVisible();
  await page.getByLabel('Harmony event draft').fill(JSON.stringify([{kind:'chord',beat:0,durationBeats:1,name:'C/E',notes:[52,60,64,67]},{kind:'rest',beat:1,durationBeats:1},{kind:'unknown',beat:2,durationBeats:1},{kind:'chord',beat:3,durationBeats:1,name:'unsupported-symbol'}]));
  await page.getByRole('button',{name:'Validate harmony preview'}).click();const preview=page.getByLabel('Unreviewed harmony candidate');await expect(preview).toContainText('N.C.');await expect(preview).toContainText('unsupported symbol is display-only');
  const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Download candidate sidecar'}).click();const file=await downloaded;const timeline=JSON.parse(await readFile((await file.path())!,'utf8'));expect(normalizeChordTimeline(timeline)).toEqual(timeline);expect(timeline.provenance.sourceRef).toContain(`:${receipt.publicationRevision}:`);expect(timeline.chords.every((c:{sourceKind:string})=>c.sourceKind==='unknown')).toBe(true);
  await page.getByRole('button',{name:'Hear unchanged Original'}).click();await expect(page.getByRole('status')).toContainText('Plain synth preview');await page.getByRole('button',{name:'Stop preview'}).click();
  expect(await readFile(path)).toEqual(original);expect((await (await request.get(`/api/songs/${id}`)).json()).publicationRevision).toBe(receipt.publicationRevision);
  await page.getByRole('button',{name:'Discard harmony draft'}).click();await expect(preview).toHaveCount(0);
  expect((await request.patch(`/api/songs/${id}`,{headers:{Authorization:headers.Authorization},data:{expectedRevision:receipt.publicationRevision,title:'Changed publication'}})).ok()).toBe(true);
  await page.getByRole('button',{name:'Validate harmony preview'}).click();await expect(page.getByRole('status')).toContainText('publication changed');expect(await readFile(path)).toEqual(original);
 }finally{expect((await request.delete(`/api/songs/${receipt.baseId}`,{headers})).ok()).toBe(true);}
});
test("frozen harmony survives reload and needs exact independent review plus owner authorization before atomic publication",async({page,request})=>{
 const headers={Authorization:"Bearer test-token-for-e2e","Content-Type":"application/xml"},created=await request.post('/api/uploads?title=Publish%20Harmony&artist=Author',{headers,data:Buffer.from(xml)});expect(created.ok(),await created.text()).toBe(true);
 const initial=await created.json(),id=initial.songIds.find((id:string)=>id.endsWith('-a')),path=join(process.env.KEYSPILLI_E2E_SCRATCH_DIR!,'artifacts',initial.baseId,'a','notes.json'),original=await readFile(path),url=`/maintenance/harmony?id=${id}&revision=${initial.publicationRevision}`;
 try{
  expect((await request.post('/api/catalog/harmony/candidates',{data:{}})).status()).toBe(401);expect((await request.put('/api/catalog/harmony/candidates',{data:{}})).status()).toBe(401);
  await page.goto(url);await page.getByRole('button',{name:'Load pinned Original'}).click();await expect(page.getByRole('heading',{name:'Publish Harmony'})).toBeVisible();
  await page.getByLabel('Harmony event draft').fill(JSON.stringify([{kind:'chord',beat:0,durationBeats:4,name:'C'},{kind:'rest',beat:4,durationBeats:4}]));await page.getByRole('button',{name:'Validate harmony preview'}).click();await expect(page.getByLabel('Unreviewed harmony candidate')).toBeVisible();
  await page.getByRole('button',{name:'Save review candidate'}).click();await expect(page.getByRole('status')).toContainText('Frozen review candidate saved');await expect(page.getByRole('button',{name:'Publish reviewed Chords backing'})).toBeDisabled();
  expect(await readFile(path)).toEqual(original);expect((await (await request.get(`/api/songs/${id}`)).json()).publicationRevision).toBe(initial.publicationRevision);
  await page.reload();await page.getByRole('button',{name:'Load pinned Original'}).click();const history=page.getByText(/Saved candidate history/);await expect(history).toBeVisible();await history.click();await page.getByRole('button',{name:/Load saved candidate/}).click();await expect(page.getByLabel('Harmony event draft')).toHaveValue(/durationBeats/);
  const templateDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download candidate pending review template'}).click();const template=JSON.parse(await readFile((await (await templateDownload).path())!,'utf8'));
  const evidence=[{id:'synthetic-browser-test',sha256:'c'.repeat(64)}];const partial={...template,reviewer:{id:'synthetic-pianist',role:'pianist',independent:true},reviewedAt:'2026-10-03T11:00:00Z',coverage:[{startBeat:0,endBeat:2}],decision:'accepted',rationale:'Synthetic browser test; no real musical approval.',checks:{source:{result:'passed',evidence},listening:{result:'passed',evidence},keyboard:{result:'passed',evidence}}};
  await page.getByLabel('Candidate review receipt JSON').fill(JSON.stringify(partial));await page.getByRole('button',{name:'Import candidate review'}).click();await expect(page.getByRole('status')).toContainText('Decision partial');await expect(page.getByRole('button',{name:'Publish reviewed Chords backing'})).toBeDisabled();
  const list=await (await request.get(`/api/catalog/harmony/candidates?id=${id}&revision=${initial.publicationRevision}`,{headers})).json(),saved=list.entries[0];
  const full={...partial,coverage:[{startBeat:0,endBeat:saved.endBeat}]};await page.getByLabel('Candidate review receipt JSON').fill(JSON.stringify(full));await page.getByRole('button',{name:'Import candidate review'}).click();await expect(page.getByRole('status')).toContainText('Decision accepted');await expect(page.getByRole('button',{name:'Publish reviewed Chords backing'})).toBeDisabled();
  await page.getByLabel('Owner publication statement').fill('Publish this exact reviewed Chords candidate.');await page.getByRole('button',{name:'Publish reviewed Chords backing'}).click();await expect(page.getByRole('status')).toContainText('Chords backing published');await expect(page.getByRole('link',{name:'Review published version'})).toBeVisible();
  const result=await (await request.get(`/api/songs/${id}`)).json();expect(result.publicationRevision).not.toBe(initial.publicationRevision);expect(result.data.sourceFingerprint).toBe(template.sourceFingerprint);expect(await readFile(path)).toEqual(original);
  const review=await (await request.get(`/api/catalog/review?after=upload`,{headers})).json(),entry=review.entries.find((item:{baseId:string})=>item.baseId===initial.baseId);expect(entry.variants[0].decisions.find((d:{mode:string})=>d.mode==='Chords').status).toBe('accepted');
  expect((await request.get(`/api/catalog/harmony/candidates?id=${id}&revision=${initial.publicationRevision}`,{headers})).status()).toBe(409);
 }finally{expect((await request.delete(`/api/songs/${initial.baseId}`,{headers})).ok()).toBe(true);}
});
