import {expect,test} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {openPlayerTool} from './player-tools';
const xml=`<score-partwise><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes>${['C','D','E','F','G','A','B','C'].map(step=>`<note><pitch><step>${step}</step><octave>4</octave></pitch><duration>1</duration></note>`).join('')}</measure></part></score-partwise>`;
test('a reviewed saved passage has explicit demonstration, guided/reduced attempts and keyboard reveal without changing targets',async({page,request})=>{
 const headers={Authorization:'Bearer test-token-for-e2e','Content-Type':'application/xml'},created=await request.post('/api/uploads?title=Recall%20Fixture&artist=Owner',{headers,data:Buffer.from(xml)});expect(created.ok(),await created.text()).toBe(true);const receipt=await created.json(),id=receipt.songIds.find((v:string)=>v.endsWith('-a')),path=join(process.env.KEYSPILLI_E2E_SCRATCH_DIR!,'artifacts',receipt.baseId,'a','notes.json'),original=await readFile(path);
 try{
  await page.addInitScript(()=>localStorage.setItem('keyspilli.prefs.v1',JSON.stringify({backgroundMode:'piano',soundSource:'synth',hand:'R',speed:1,transpose:0})));await page.goto(`/player/${id}/beginner`);await page.locator('.player-loop-controls > summary').click();await page.getByRole('button',{name:'Loop current bar',exact:true}).click();await page.locator('.player-loop-controls > summary').click();
  const workspace=page.getByLabel('Saved passages and practice history');await workspace.locator(':scope > summary').click();await workspace.getByLabel('Passage name').fill('Reviewed phrase');await workspace.getByRole('button',{name:'Save selected loop',exact:true}).click();await workspace.getByRole('checkbox',{name:/A competent player has reviewed/}).check();await workspace.getByRole('button',{name:'Try recall for Reviewed phrase'}).click();const recall=page.getByLabel('Passage recall trial');await expect(recall.getByRole('button',{name:'2. Guided passage attempt'})).toBeDisabled();await recall.getByRole('button',{name:'1. Demonstrate saved passage'}).click();await expect(recall.getByRole('button',{name:'2. Guided passage attempt'})).toBeEnabled({timeout:6000});
  const start=async(button:string)=>{await recall.getByRole('button',{name:button}).click();const setup=page.getByRole('dialog',{name:'Set up practice'});await expect(setup.getByLabel('Passage',{exact:true})).toHaveValue('loop');await setup.getByLabel('Behavior').selectOption('wait');await setup.getByLabel('Count-in',{exact:true}).selectOption('0');await setup.getByRole('button',{name:'Start practice',exact:true}).click();await expect(page.locator('.player-stage')).toBeFocused();};
  await start('2. Guided passage attempt');const grading=page.getByLabel('Practice grading');for(const [pitch,key] of [['C4','a'],['D4','s'],['E4','d'],['F4','f']]){await expect(grading.getByRole('status')).toContainText(pitch!);await page.keyboard.press(key!);}await expect(grading).toContainText('100% onset accuracy');await expect(recall.getByRole('button',{name:'3. Try reduced pitch cues'})).toBeEnabled();
  await start('3. Try reduced pitch cues');await expect(page.locator('.note-letter-badge[data-midi]')).toHaveCount(0);await expect(grading).toContainText('Pitch cues reduced');await page.keyboard.press('a');await page.keyboard.press('s');const before=await page.getByRole('slider',{name:'Seek',exact:true}).inputValue();await recall.getByRole('button',{name:'Reveal / Restore guidance'}).press('Enter');expect(await page.getByRole('slider',{name:'Seek',exact:true}).inputValue()).toBe(before);await expect(page.locator('.note-letter-badge[data-midi]').first()).toBeVisible();await page.locator('.player-stage').focus();await page.keyboard.press('d');await page.keyboard.press('f');await expect(grading).toContainText('100% onset accuracy');
  const runs=await page.evaluate(()=>JSON.parse(localStorage.getItem('keyspilli.practice.v1')!).attempts);expect(runs[0].context.assistance).toMatchObject({mode:'reduced-pitch',reveals:1,review:'owner-confirmed-trial'});expect(runs[1].context.assistance.mode).toBe('guided');expect(runs[0].target).toEqual(runs[1].target);expect([runs[0].result.hit,runs[0].result.missed,runs[0].result.wrong,runs[0].result.accuracyPct]).toEqual([runs[1].result.hit,runs[1].result.missed,runs[1].result.wrong,runs[1].result.accuracyPct]);expect(await readFile(path)).toEqual(original);
  await recall.getByRole('button',{name:'3. Try reduced pitch cues'}).click();await page.getByRole('dialog',{name:'Set up practice'}).press('Escape');await expect(page.locator('.note-letter-badge[data-midi]').first()).toBeVisible();await start('3. Try reduced pitch cues');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await expect(page.locator('.note-letter-badge[data-midi]').first()).toBeVisible();await expect(recall).toContainText('Guidance visible');await openPlayerTool(page,'Sound');await page.getByRole('radio',{name:'Organ',exact:true}).click();await page.getByRole('button',{name:'Close tools',exact:true}).click();await expect(recall).toHaveCount(0);await expect(page.locator('.note-letter-badge[data-midi]').first()).toBeVisible();expect(await readFile(path)).toEqual(original);
 }finally{expect((await request.delete(`/api/songs/${receipt.baseId}`,{headers})).ok()).toBe(true);}
});
