import { readFileSync } from "node:fs";
import { expect, test } from "@playwright/test";
import { KEYMAP } from "../../../packages/player-core/src/input";

const xml = `<?xml version="1.0"?><score-partwise version="4.0"><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><key><fifths>0</fifths></key><time><beats>4</beats><beat-type>4</beat-type></time></attributes>${["C", "D", "E", "F", "G", "A", "B", "C"].map(step => `<note><pitch><step>${step}</step><octave>4</octave></pitch><duration>1</duration><type>quarter</type></note>`).join("")}</measure></part></score-partwise>`;

test("version-bound passages reload and cancelled/completed/interrupted runs stay distinct", async ({ page, request }) => {
  const uploaded = await request.post("/api/uploads?title=Roadmap%20Practice%20Fixture&artist=Authored%20Test", {
    headers: { Authorization: "Bearer test-token-for-e2e", "Content-Type": "application/xml" }, data: Buffer.from(xml),
  });
  expect(uploaded.status(), await uploaded.text()).toBe(200);
  const { baseId, songIds } = await uploaded.json();
  const id = songIds.find((songId: string) => songId.endsWith("-a"));
  expect(id).toBeDefined();
  try {
    await page.addInitScript(() => {
      localStorage.setItem("keyspilli.prefs.v1", JSON.stringify({ soundSource: "synth", hand: "R" }));
      const NativeContext = window.AudioContext;
      const state = window as unknown as { __practiceContexts: AudioContext[] };
      state.__practiceContexts = [];
      window.AudioContext = class extends NativeContext { constructor(options?: AudioContextOptions) { super(options); state.__practiceContexts.push(this); } };
    });
    await page.goto(`/player/${id}/beginner`);
    await page.locator(".player-loop-controls > summary").click();
    await page.getByRole("button", { name: "Loop current bar", exact: true }).click();
    await page.locator(".player-loop-controls > summary").click();
    const workspace = page.locator('details[aria-label="Saved passages and practice history"]');
    await workspace.locator(":scope > summary").click();
    await workspace.getByLabel("Passage name").fill("First phrase");
    await workspace.getByLabel("Practice note").fill("Relax between notes");
    await expect(workspace.getByRole("button", { name: "Save selected loop" })).toBeEnabled();
    await workspace.getByRole("button", { name: "Save selected loop" }).click();
    const sets = workspace.locator('details[aria-label="Owner practice sets"]');
    await sets.locator(":scope > summary").click();
    await sets.getByLabel("New practice set").fill("Daily Fixture");
    await sets.getByRole("button", { name: "Create set", exact: true }).click();
    const passageId = await page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).passages[0].id);
    await sets.getByLabel("Practice set passage").selectOption(passageId);
    await sets.getByRole("button", { name: "Add chosen arrangement" }).click();
    await sets.getByLabel("Practice set passage").selectOption("");
    await sets.getByRole("button", { name: "Add chosen arrangement" }).click();
    await expect(sets.locator("[data-set-item]")).toHaveCount(2);
    await sets.getByRole("button", { name: "Move Roadmap Practice Fixture up", exact: true }).nth(1).press("Enter");
    await sets.getByLabel("Manually completed Roadmap Practice Fixture").first().check();
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice-sets.v1")!).sets[0].items.map((item: { passageId?: string; completed: boolean }) => [item.passageId ?? null, item.completed]))).toEqual([[null,true],[passageId,false]]);
    await expect(sets.getByRole("link", { name: "Next unfinished item" })).toHaveAttribute("href", `/player/${id}?passage=${passageId}`);
    await page.evaluate(() => { const state = JSON.parse(localStorage.getItem("keyspilli.practice-sets.v1")!); state.sets[0].items.push({id:"missing",baseId:"missing-owner",variantId:"missing-owner-level",completed:false}); localStorage.setItem("keyspilli.practice-sets.v1",JSON.stringify(state)); window.dispatchEvent(new Event("keyspilli-practice-sets")); });
    await expect(sets.getByText("missing-owner-level · Unavailable; original reference retained", { exact: true })).toBeVisible();

    await page.reload();
    await workspace.locator(":scope > summary").click();
    await expect(workspace.getByText("Relax between notes")).toBeVisible();
    await workspace.getByRole("button", { name: "Select First phrase", exact: true }).click();
    await page.getByRole("button", { name: "Practice", exact: true }).click();
    let dialog = page.getByRole("dialog", { name: "Set up practice" });
    await dialog.getByLabel("Passage", { exact: true }).selectOption("loop");
    await dialog.getByLabel("Behavior").selectOption("wait");
    await dialog.getByLabel("Count-in", { exact: true }).selectOption("4");
    await dialog.getByRole("button", { name: "Start practice", exact: true }).click();
    await page.getByRole("button", { name: "Cancel count-in", exact: true }).click();
    await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).attempts[0].outcome)).toBe("cancelled");
    await page.getByRole("button", { name: "Practice", exact: true }).click();
    dialog = page.getByRole("dialog", { name: "Set up practice" });
    await dialog.getByLabel("Passage", { exact: true }).selectOption("loop");
    await dialog.getByLabel("Behavior").selectOption("wait");
    await dialog.getByLabel("Count-in", { exact: true }).selectOption("0");
    await dialog.getByRole("button", { name: "Start practice", exact: true }).click();
    const detail = await (await request.get(`/api/songs/${id}`)).json();
    expect(detail.publicationRevision).toBeTruthy();
    const pinned = await request.get(`/api/song/${id}/export?type=midi&revision=${encodeURIComponent(detail.publicationRevision)}`);
    expect(pinned.status()).toBe(200);
    expect(pinned.headers()["x-publication-revision"]).toBe(detail.publicationRevision);
    expect((await pinned.body()).subarray(0, 4).toString()).toBe("MThd");
    expect((await request.get(`/api/song/${id}/export?type=midi&revision=stale-browser-pin`)).status()).toBe(409);
    const targets = detail.data.notes.filter((note: { start: number; dur: number; hand: string }) => note.start < 4 && note.dur >= 0.25 && note.hand !== "L");
    expect(targets.length).toBeGreaterThan(0);
    await page.locator(".player-stage").click();
    for (const note of targets) {
      const key = Object.entries(KEYMAP).find(([, midi]) => midi === note.midi)?.[0];
      expect(key).toBeDefined();
      await page.keyboard.press(key!);
    }
    await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).attempts[0].outcome)).toBe("completed");
    await page.reload();
    const runs = await page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).attempts);
    expect(runs.map((run: { outcome: string }) => run.outcome)).toEqual(["completed", "cancelled"]);
    expect(runs[0].result.accuracyPct).toBe(100);
    await workspace.locator(":scope > summary").click();
    await workspace.getByRole("button", { name: "Select First phrase", exact: true }).click();
    const ladder = workspace.locator('details[aria-label="Tempo plan for First phrase"]');
    await ladder.locator(":scope > summary").click();
    const bpm = detail.data.tempoBpm;
    await ladder.getByLabel("Starting BPM for First phrase").fill(String(bpm));
    await ladder.getByLabel("Target BPM for First phrase").fill(String(bpm+5));
    await ladder.getByLabel("Runs per tempo").fill("1");
    await ladder.getByRole("button", { name: "Save tempo plan", exact: true }).click();
    await ladder.getByRole("button", { name: `Use plan tempo ${bpm} BPM`, exact: true }).click();
    await page.getByRole("button", { name: "Practice", exact: true }).click();
    dialog = page.getByRole("dialog", { name: "Set up practice" });
    await dialog.getByLabel("Passage", { exact: true }).selectOption("loop");
    await dialog.getByLabel("Behavior").selectOption("wait");
    await dialog.getByLabel("Count-in", { exact: true }).selectOption("0");
    await dialog.getByRole("button", { name: "Start practice", exact: true }).click();
    await page.locator(".player-stage").click();
    await page.keyboard.press("w");
    for (const note of targets) await page.keyboard.press(Object.entries(KEYMAP).find(([, midi]) => midi === note.midi)![0]);
    const problem = page.getByRole("button", { name: "Revisit difficult passage 1", exact: false });
    await expect(problem).toBeVisible();
    const flawed = await page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).attempts[0]);
    expect(flawed.result.wrong).toBe(1);
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).passages[0].tempoPlan.currentBpm)).toBe(bpm);
    expect(flawed.result.diagnostics.events.some((event: { outcome: string }) => event.outcome === "wrong")).toBe(true);
    await problem.click();
    await expect(problem).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Play", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Practice", exact: true }).click();
    dialog = page.getByRole("dialog", { name: "Set up practice" });
    await dialog.getByLabel("Behavior").selectOption("wait");
    await dialog.getByRole("button", { name: "Start practice", exact: true }).click();
    await page.evaluate(async () => { const contexts = (window as unknown as { __practiceContexts: AudioContext[] }).__practiceContexts; const context = [...contexts].reverse().find(item => item.state !== "closed"); if (!context) throw Error("No practice audio context"); await context.suspend(); });
    await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).attempts[0].outcome)).toBe("interrupted");
    await expect(page.getByText("Audio output was interrupted.", { exact: false })).toBeVisible();
    await page.getByRole("button", { name: "Practice", exact: true }).click();
    dialog = page.getByRole("dialog", { name: "Set up practice" });
    await dialog.getByLabel("Behavior").selectOption("wait");
    await dialog.getByRole("button", { name: "Start practice", exact: true }).click();
    await page.evaluate(() => window.dispatchEvent(new Event("blur")));
    await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).attempts[0].outcome)).toBe("interrupted");
    await expect(page.getByText("Window focus was lost.", { exact: false })).toBeVisible();
    await ladder.getByRole("button", { name: `Use plan tempo ${bpm} BPM`, exact: true }).click();
    await page.getByRole("button", { name: "Practice", exact: true }).click();
    dialog = page.getByRole("dialog", { name: "Set up practice" });
    await dialog.getByLabel("Behavior").selectOption("along");
    await dialog.getByLabel("Count-in", { exact: true }).selectOption("0");
    await dialog.getByRole("button", { name: "Start practice", exact: true }).click();
    const scheduled = targets.map((note: { start: number; midi: number }) => ({ beat: note.start, key: Object.entries(KEYMAP).find(([,midi]) => midi === note.midi)![0] }));
    await page.evaluate(async ({ notes, bpm }) => {
      const began = performance.now();
      for (const note of notes) {
        await new Promise(resolve => setTimeout(resolve, Math.max(0,note.beat*60_000/bpm-(performance.now()-began))));
        window.dispatchEvent(new KeyboardEvent("keydown", {key:note.key,bubbles:true}));
        window.dispatchEvent(new KeyboardEvent("keyup", {key:note.key,bubbles:true}));
      }
    }, { notes:scheduled, bpm });
    await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).attempts[0].outcome)).toBe("completed");
    await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).passages[0].tempoPlan.currentBpm)).toBe(bpm+5);
    await ladder.getByRole("button", { name: `Use plan tempo ${bpm+5} BPM`, exact: true }).click();
    await expect(page.getByRole("button", { name: "Play", exact: true })).toBeVisible();
    await ladder.getByRole("button", { name: "Pause plan", exact: true }).click();
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).passages[0].tempoPlan.paused)).toBe(true);
    const backup = page.locator('details[aria-label="Back up browser practice"]');
    await backup.locator(":scope > summary").click();
    await backup.getByLabel("Include private practice history").check();
    const downloadEvent = page.waitForEvent("download");
    await backup.getByRole("button", { name: "Download owner state" }).click();
    const download = await downloadEvent, exported = readFileSync((await download.path())!, "utf8");
    const document = JSON.parse(exported);
    expect(document.practiceSets.sets[0].name).toBe("Daily Fixture");
    expect(document.practice.passages[0].name).toBe("First phrase"); expect(document.practice.attempts.length).toBeGreaterThan(0);
    await page.evaluate(() => localStorage.setItem("keyspilli.favorites", '["unrelated-owner-level"]'));
    await backup.getByLabel("Preview restore").setInputFiles({ name: "owner-state.json", mimeType: "application/json", buffer: Buffer.from(exported) });
    await expect(backup.getByText("Preview only; nothing changed.", { exact: true })).toBeVisible();
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.favorites")!))).toEqual(["unrelated-owner-level"]);
    await backup.getByRole("button", { name: "Apply merge restore" }).click();
    await expect(backup.getByRole("status")).toContainText("Restored. Reload");
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.favorites")!))).toContain("unrelated-owner-level");
    await page.goto("/");
    const home = page.getByRole("region", { name: "Your practice workspace" });
    await expect(home.getByRole("link", { name: /Open last practice: Roadmap Practice Fixture/ })).toHaveAttribute("href", `/player/${id}`);
    const homeSets = page.locator('details[aria-label="Owner practice sets"]');
    await homeSets.locator(":scope > summary").click();
    await homeSets.getByRole("link", { name: "Next unfinished item" }).click();
    await expect(page.locator(".player-loop-controls")).toHaveAttribute("data-active", "true");
    await expect(page.getByRole("button", { name: "Play", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Play", exact: true })).toBeVisible();
    await page.goto("/songs");
    await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("keyspilli.practice.v1")!).attempts[0].outcome)).toBe("completed");
  } finally {
    const deleted = await request.delete(`/api/songs/${baseId}`, { headers: { Authorization: "Bearer test-token-for-e2e" } });
    expect(deleted.ok()).toBe(true);
  }
});
