import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
const headers={Authorization:'Bearer test-token-for-e2e','Content-Type':'application/xml'};
test('rhythm-only taps retain raw offsets, complete separately and cancel without altering target or history',async({page,request})=>{
 const xml='<score-partwise><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1">'+Array.from({length:4},(_,i)=>`<measure number="${i+1}">${i===0?'<attributes><divisions>1</divisions><time><beats>3</beats><beat-type>4</beat-type></time></attributes>':''}${['C','D','E'].map(step=>`<note><pitch><step>${step}</step><octave>4</octave></pitch><duration>1</duration><type>quarter</type></note>`).join('')}</measure>`).join('')+'</part></score-partwise>';
 const response=await request.post('/api/uploads?title=Rhythm%20Fixture&artist=Fixture',{headers,data:Buffer.from(xml)});expect(response.ok(),await response.text()).toBe(true);const receipt=await response.json(),id=receipt.songIds.find((v:string)=>v.endsWith('-a')),path=join(process.env.KEYSPILLI_E2E_SCRATCH_DIR!,'artifacts',receipt.baseId,'a','notes.json'),before=await readFile(path);
 try{
  await page.goto(`/player/${id}/beginner`);const history=await page.evaluate(()=>localStorage.getItem('keyspilli.practice.v1'));
  const coach=page.getByLabel('Rhythm-only passage coach');await coach.locator('summary').click();await coach.getByLabel('Rhythm cues',{exact:true}).selectOption('quarter');await coach.getByLabel('Manual tap offset (ms)').fill('37');await coach.getByRole('button',{name:'Start rhythm-only attempt'}).click();await expect(coach.getByLabel('Rhythm status')).toContainText('Get ready');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Practice',exact:true})).toBeDisabled();
  await page.waitForTimeout(1100);await coach.getByRole('button',{name:'Rhythm tap',exact:true}).focus();await page.keyboard.press('Space');await expect(coach.getByLabel('Rhythm status')).toContainText('1 taps');await expect(coach.getByLabel('Rhythm-only result')).toBeVisible({timeout:15000});
  const event=page.waitForEvent('download');await coach.getByRole('button',{name:'Download raw rhythm taps'}).click();const downloaded=await event,file=await downloaded.path();expect(file).not.toBeNull();const raw=JSON.parse(await readFile(file!,'utf8'));expect(raw.kind).toBe('rhythm-only-taps');expect(raw.manualOffsetMs).toBe(37);expect(raw.cueMode).toBe('quarter');expect(raw.targetStartsSec).toHaveLength(12);expect(raw.events).toHaveLength(1);expect(raw.events[0].rawSec-raw.events[0].adjustedSec).toBeCloseTo(.037,9);
  await coach.getByRole('button',{name:'Remove rhythm take'}).click();await expect(coach.getByRole('button',{name:'Download raw rhythm taps'})).toHaveCount(0);
  await coach.getByRole('button',{name:'Start rhythm-only attempt'}).click();await coach.getByRole('button',{name:'Stop rhythm attempt'}).click();await expect(coach.getByLabel('Rhythm status')).toContainText('cancelled');await expect(page.getByRole('button',{name:'Play',exact:true})).toBeEnabled();expect(await page.evaluate(()=>localStorage.getItem('keyspilli.practice.v1'))).toBe(history);expect(await readFile(path)).toEqual(before);
 }finally{expect((await request.delete(`/api/songs/${receipt.baseId}`,{headers})).ok()).toBe(true);}
});
