import {expect,test} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {parseMidi,parseMusicXmlNotes,writeMidi} from '@keyspilli/midi';
test('reviewed private source CC64 survives upload, active exports and metadata rebuilding',async({page,request})=>{
 const token={Authorization:'Bearer test-token-for-e2e'},notes=[{midi:60,start:0,dur:1,vel:71,hand:'R' as const,sourceMidiChannel:2}],sourcePedal={version:1 as const,endBeat:4,provenance:'midi-file' as const,changes:[{beat:0,channel:2,value:127,source:'midi:0'},{beat:3,channel:2,value:0,source:'midi:0'}]},bytes=Buffer.from(writeMidi(notes,{tempoBpm:120,sourcePedal,tracks:[{name:'Right Hand',notes}]}));
 const preflightResponse=await request.post('/api/uploads/preflight',{headers:{...token,'Content-Type':'audio/midi'},data:bytes});expect(preflightResponse.ok(),await preflightResponse.text()).toBe(true);const preflight=await preflightResponse.json();
 const choice={selectedParts:[{id:preflight.parts[0].id,role:'other'}],arrangementIntent:'original',rightsAttested:true,ownerAuthoredStudy:true};
 const created=await request.post('/api/uploads?title=Source%20Pedal%20Study&artist=Owner',{headers:{...token,'Content-Type':'audio/midi','X-Keyspilli-Upload-Preflight':preflight.preflightId,'X-Keyspilli-Upload-Choice':JSON.stringify(choice)},data:bytes});expect(created.ok(),await created.text()).toBe(true);const receipt=await created.json(),id=receipt.songIds.find((s:string)=>s.endsWith('-a'));
 try{
  const root=process.env.KEYSPILLI_E2E_SCRATCH_DIR!,file=join(root,'artifacts',receipt.baseId,'a','notes.json'),original=await readFile(file);
  const detail=await(await request.get(`/api/songs/${id}`)).json();expect(detail.data.sourcePedal.changes.map((e:{beat:number;channel:number;value:number})=>[e.beat,e.channel,e.value])).toEqual([[0,2,127],[3,2,0]]);expect(detail.data.notes[0].dur).toBe(1);
  await page.addInitScript(()=>localStorage.setItem('keyspilli.prefs.v1',JSON.stringify({soundSource:'synth',backgroundMode:'piano',hand:'both',speed:1,transpose:0,sustainPedal:true})));await page.goto(`/player/${id}/beginner`);await expect(page.getByText('Source-file CC64 controls resonance separately from key holds.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Download sheet music and MIDI'}).click();const dialog=page.getByRole('dialog',{name:'Download sheet music or MIDI'});await dialog.getByRole('combobox',{name:'Arrangement'}).selectOption('active');
  for(const [button,format] of [['Active MIDI','midi'],['Active MusicXML','xml']]){const download=page.waitForEvent('download');await dialog.getByRole('button',{name:button,exact:true}).click();const filePath=await(await download).path(),content=await readFile(filePath!);const parsed=format==='midi'?parseMidi(content):parseMusicXmlNotes(content.toString());expect(parsed.sourcePedal?.changes.map(e=>[e.beat,e.channel,e.value])).toEqual([[0,2,127],[3,2,0]]);expect(parsed.notes[0]!.dur).toBe(1);expect(parsed.notes[0]!.sourceMidiChannel).toBe(2);}
  expect(await readFile(file)).toEqual(original);
  const updated=await request.patch(`/api/songs/${id}`,{headers:token,data:{expectedRevision:receipt.publicationRevision,title:'Retained source pedal'}});expect(updated.ok(),await updated.text()).toBe(true);expect(await readFile(file)).toEqual(original);
  const current=await(await request.get(`/api/songs/${id}`)).json();const calibration=await request.patch(`/api/songs/${id}`,{headers:token,data:{expectedRevision:current.publicationRevision,calibrationTempo:180}});expect(calibration.ok(),await calibration.text()).toBe(true);const rebuilt=await(await request.get(`/api/songs/${id}`)).json();expect(rebuilt.data.notes[0].dur).toBe(1.5);expect(rebuilt.data.sourcePedal.changes[1].beat).toBe(4.5);expect(rebuilt.data.sourcePedal.endBeat).toBe(6);
  const stored=await request.get(`/api/song/${id}/export?type=midi&revision=${rebuilt.publicationRevision}`);expect(stored.ok(),await stored.text()).toBe(true);expect(parseMidi(await stored.body()).sourcePedal?.changes[1]!.beat).toBe(4.5);
 }finally{expect((await request.delete(`/api/songs/${receipt.baseId}`,{headers:token})).ok()).toBe(true);}
});
