import React,{useEffect,useRef,useState} from "react";
import {createRoot} from "react-dom/client";
import {AudioEngine,PlaybackEngine,KeyboardInput,DEFAULT_SETTINGS,resolveSourcePedalNotes,resolveTimedNotes,secPerBeat,learnerPitch,type GradeResult} from "@keyspilli/player-core";
import {BeginnerView} from "../components/player/BeginnerView";
import {loadOfflinePack,removeOfflinePack,type OfflinePack} from "../lib/offline-pack";
const settings={...DEFAULT_SETTINGS,soundSource:"synth" as const,mode:"beginner" as const,sustainPedal:false};
function OfflinePlayer(){
 const [pack,setPack]=useState<OfflinePack|null>(null),[unlocked,setUnlocked]=useState(false),[notice,setNotice]=useState(""),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[result,setResult]=useState<GradeResult|null>(null),[waiting,setWaiting]=useState<number[]>([]);
 const engine=useRef<PlaybackEngine|null>(null),keyboard=useRef<KeyboardInput|null>(null),stage=useRef<HTMLDivElement|null>(null),generation=useRef(0);
 function stop(){keyboard.current?.releaseAll();engine.current?.finishGrading();engine.current?.stop();engine.current?.audio.cancelAll();setPlaying(false);setWaiting([]);}
 function lock(){stop();setUnlocked(false);setResult(null);setTime(0);}
 useEffect(()=>{
  let live=true;async function load(){const turn=++generation.current;lock();setPack(null);try{const value=await loadOfflinePack();if(live&&generation.current===turn){setPack(value);setNotice(value?"Local screen lock. Unlock only on your private device.":"No selected pack. Prepare one online; uncached songs require network.");}}catch(error){if(live&&generation.current===turn)setNotice(error instanceof Error?error.message:"Offline storage unavailable.");}}
  void load();const channel=typeof BroadcastChannel!=="undefined"?new BroadcastChannel("keyspilli.offline"):null;if(channel)channel.onmessage=()=>void load();const hidden=()=>{if(document.hidden)lock();};const leaving=()=>lock();document.addEventListener("visibilitychange",hidden);window.addEventListener("pagehide",leaving);window.addEventListener("blur",leaving);
  return ()=>{live=false;generation.current++;channel?.close();document.removeEventListener("visibilitychange",hidden);window.removeEventListener("pagehide",leaving);window.removeEventListener("blur",leaving);};
 },[]);
 useEffect(()=>{
  if(!pack||!unlocked)return;
  const audio=new AudioEngine(),notes=resolveSourcePedalNotes(pack.data,1,0),guidance=resolveTimedNotes(pack.data,1,0),duration=Math.max(...notes.map(n=>n.startSec+(n.soundingDurSec??n.durSec))),owner=new PlaybackEngine(audio,notes,duration,{tempoBpm:pack.data.tempoBpm,timeSig:pack.data.timeSig},settings,[],guidance);
  engine.current=owner;keyboard.current=new KeyboardInput({onNoteOn:(midi,_id,event)=>owner.handleNoteOn(midi,event),onNoteOff:midi=>owner.handleNoteOff(midi)});
  owner.onChange=s=>{setTime(s.time);setPlaying(s.playing);setResult(owner.gradeResult);setWaiting(owner.waitNotes.map(n=>n.midi));};
  const interrupt=()=>{if(owner.playing||owner.grader){stop();setNotice("Playback interrupted. Restart deliberately; no device timing or mastery is measured.");}};audio.onStateChange=state=>{if(state!=="running")interrupt();};
  let frame=0,last=performance.now();const tick=(now:number)=>{const delta=(now-last)/1000;last=now;if(Date.now()>=Date.parse(pack.expiresAt)){lock();setPack(null);void removeOfflinePack().then(()=>setNotice("Expired pack removed."),()=>setNotice("Pack expired; storage removal failed. Retry Remove pack."));return;}if(delta>.3)interrupt();else owner.tick(delta);frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);
  return ()=>{cancelAnimationFrame(frame);keyboard.current?.releaseAll();keyboard.current=null;owner.onChange=null;audio.onStateChange=null;owner.finishGrading();owner.stop();audio.dispose();if(engine.current===owner)engine.current=null;};
 },[pack,unlocked]);
 async function remove(){lock();try{await removeOfflinePack();setPack(null);setNotice("Private pack removed from this browser. Downloaded copies are separate.");}catch{setNotice("Removal failed; close other offline tabs and retry.");}}
 async function stale(){if(!pack)return;setNotice("Checking current publication online…");try{const response=await fetch(`/api/songs/${encodeURIComponent(pack.variantId)}?revision=${encodeURIComponent(pack.revision)}`,{cache:"no-store",signal:AbortSignal.timeout(3000)});setNotice(response.status===409||response.status===404?"Stored pack is stale or no longer published. Remove it and prepare a fresh pack online.":response.ok?"Publication still matches this stored revision. Offline revocation of local copies is not promised.":"Current publication could not be checked. Stored snapshot remains local.");}catch{setNotice("Offline: current publication is unknown. This is the stored snapshot, not a freshness guarantee.");}}
 function start(practice:boolean){const owner=engine.current;if(!owner)return;stop();owner.seek(0);setNotice("");try{if(practice)owner.startGrading(true,{startSec:0,endSec:owner.duration});else owner.start();stage.current?.focus();}catch{setNotice("Playback unavailable; unlock again or prepare a supported pack online.");}}
 function artifact(kind:"midi"|"musicxml"){if(!pack)return;const item=pack.artifacts[kind],url=URL.createObjectURL(new Blob([Uint8Array.from(atob(item.base64),c=>c.charCodeAt(0))],{type:kind==="midi"?"audio/midi":"application/vnd.recordare.musicxml+xml"}));const link=document.createElement("a");link.href=url;link.download=`${pack.variantId}-stored.${kind==="midi"?"mid":"musicxml"}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <main><h1>Private offline practice</h1><p>One selected Original, at most 8 MiB. Internal synth only; no microphone, MIDI devices, samples, source acquisition or cloud history. Other songs need a network connection.</p><p>Local screen lock is not encryption or an identity check. People with access to this browser can read stored music. Expiry uses this device’s clock; removal cannot revoke exported copies.</p><p role="status">{notice}</p><button onClick={()=>void remove()}>Remove pack</button>{pack&&!unlocked&&<button onClick={()=>{if(Date.now()>=Date.parse(pack.expiresAt)){void remove();setNotice("Pack expired; prepare a fresh pack online.");return;}setUnlocked(true);setNotice("Stored snapshot unlocked. Current online publication is unverified.");}}>Unlock private pack on this device</button>}
  {pack&&unlocked&&<><h2>{pack.title} — {pack.artist}</h2><p>Stored publication: {pack.revision} · Expires {pack.expiresAt}. Source musical/keyboard acceptance remains separate.</p><button onClick={lock}>Lock pack</button><button onClick={()=>void stale()}>Check current publication online</button><button onClick={()=>artifact("midi")}>Download stored MIDI</button><button onClick={()=>artifact("musicxml")}>Download stored MusicXML</button><div><button onClick={()=>start(false)}>Play stored Original</button><button onClick={()=>start(true)} disabled={pack.data.notes.some(n=>n.midi<36||n.midi>100)}>Practice stored notes with computer keys</button><button onClick={stop}>Stop sound / practice</button></div><p>Computer keys A–K and upper row sharps; Z/X changes octave. Assessed note onsets only. Physical hands, holds and latency are not measured. Targets outside computer-key reach disable practice.</p><label>Seek <input type="range" min={0} max={Math.max(...pack.data.notes.map(n=>(n.start+n.dur)*secPerBeat(pack.data.tempoBpm,1)))} step="0.01" value={time} disabled={!!engine.current?.grader} onChange={e=>engine.current?.seek(Number(e.target.value))}/></label><p role="status">{waiting.length?`Wait for ${waiting.map(m=>learnerPitch({midi:m},0,pack.data.key).label).join(" + ")}`:playing?"Playing stored Original":"Stopped"}</p>{result&&<p aria-label="Offline practice result">{result.accuracyPct}% onset accuracy · {result.hit} hit · {result.missed} missed · {result.wrong} wrong. Local session only.</p>}<div ref={stage} tabIndex={0} role="region" aria-label="Offline note-letter practice" onKeyDown={e=>keyboard.current?.handleKey(e.nativeEvent)} onKeyUp={e=>keyboard.current?.handleKey(e.nativeEvent)}><BeginnerView data={pack.data} time={time} settings={settings} chords={pack.data.chords}/></div></>}
  <p><a href="/songs">Open library online</a></p></main>;
}
createRoot(document.getElementById("offline-root")!).render(<OfflinePlayer/>);
