import {afterAll,expect,it} from "vitest";
import {mkdtempSync} from "node:fs";
import {readFile,writeFile,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {getDb,getSong,getSongsByBase,ingestSource,catalogRecoveryInventory,recoverCatalogPublication} from "@keyspilli/catalog";
import {loadSongArtifact,withStablePublication} from "./catalog-api";
import {buildHarmonyCandidate} from "./harmony-candidate";
import {saveHarmonyCandidate,importHarmonyReview,publishHarmonyCandidate} from "./harmony-publication";
import {musicalOutput,readMusicalReviews} from "./owner-admission";
import {ownerReviewList} from "./owner-review";
const old=process.env.KEYSPILLI_DATA_DIR,root=mkdtempSync(join(tmpdir(),"keyspilli-harmony-publication-"));process.env.KEYSPILLI_DATA_DIR=root;
afterAll(async()=>{getDb().close();if(old===undefined)delete process.env.KEYSPILLI_DATA_DIR;else process.env.KEYSPILLI_DATA_DIR=old;await rm(root,{recursive:true,force:true});});
it("saves and reviews frozen candidates, then publishes only the exact authorized backing while preserving Original and exclusions",async()=>{
 await writeFile(join(root,"manifest.json"),JSON.stringify({songs:[]}));
 const buf=Buffer.from(`<score-partwise><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes>${['C','D','E','F','G','A','B','C'].map(step=>`<note><pitch><step>${step}</step><octave>4</octave></pitch><duration>1</duration></note>`).join('')}</measure></part></score-partwise>`);
 const baseId="harmony-fixture",id=`${baseId}-a`;
 expect((await ingestSource({baseId,buf,title:"Harmony fixture",artist:"Authored",category:"Test",contentType:"standard"})).error).toBeUndefined();
 await writeFile(join(root,"learner-review.json"),JSON.stringify({verdicts:{[baseId]:{blocked:true}}}));
 const revision=(await withStablePublication(baseId,undefined,async()=>null)).publicationRevision!;
 const row=getSongsByBase(baseId).find(row=>row.id===id)!,data=(await loadSongArtifact(row)).data!;
 const events=[{kind:"chord",beat:0,durationBeats:4,name:"C"},{kind:"rest",beat:4,durationBeats:4}];
 const preview=buildHarmonyCandidate(data,{id,baseId,title:row.title,artist:row.artist,revision},events);
 const request={id,revision,sourceFingerprint:data.sourceFingerprint!,events,previewDigest:preview.digest,previewPlaybackSha256:preview.playbackSha256};
 const saved=await saveHarmonyCandidate(request);expect(saved.summary.status).toBe("pending");
 expect((await saveHarmonyCandidate(request)).candidateSha256).toBe(saved.candidateSha256);
 const paths=getSongsByBase(baseId).flatMap(row=>["notes.json","variant.mid","variant.xml"].map(file=>join(root,"artifacts",baseId,row.level,file)));
 const before=await Promise.all(paths.map(path=>readFile(path)));
 const authorize={id,revision,candidateSha256:saved.candidateSha256,receiptSha256s:[] as string[],ownerStatement:"Publish this exact Chords candidate.",approvedModes:["Chords"]};
 await expect(publishHarmonyCandidate(authorize)).rejects.toThrow(/review/);
 const evidence=[{id:"synthetic-independent-test",sha256:"c".repeat(64)}];
 const review={schemaVersion:1,kind:"musical-review-receipt",...saved.identity,reviewer:{id:"synthetic-pianist",role:"pianist",independent:true},reviewedAt:"2026-10-03T11:00:00Z",coverage:[{startBeat:0,endBeat:saved.endBeat}],decision:"accepted",rationale:"Synthetic transport test only, not real musical approval.",checks:{source:{result:"passed",evidence},listening:{result:"passed",evidence},keyboard:{result:"passed",evidence}}};
 const imported=await importHarmonyReview(id,revision,saved.candidateSha256,review);expect(imported.summary.status).toBe("accepted");
 authorize.receiptSha256s=[imported.receiptSha256];
 const frozen=join(root,"harmony-candidates",baseId,saved.candidateSha256,"backing.mid"),bytes=await readFile(frozen);await writeFile(frozen,Buffer.concat([bytes,Buffer.from("changed")]));
 await expect(publishHarmonyCandidate(authorize)).rejects.toThrow(/hash|frozen/);await writeFile(frozen,bytes);
 const canceled=new AbortController();canceled.abort();await expect(publishHarmonyCandidate(authorize,canceled.signal)).rejects.toThrow();
 const during=new AbortController(),attempt=publishHarmonyCandidate(authorize,during.signal);queueMicrotask(()=>during.abort());await expect(attempt).rejects.toThrow(/canceled/);
 expect((await withStablePublication(baseId,undefined,async()=>null)).publicationRevision).toBe(revision);
 const published=await publishHarmonyCandidate(authorize);expect(published.publicationRevision).not.toBe(revision);
 expect((await publishHarmonyCandidate(authorize)).publicationRevision).toBe(published.publicationRevision);
 expect(await Promise.all(paths.map(path=>readFile(path)))).toEqual(before);expect(getSong(id)).toBeUndefined();
 expect((await musicalOutput(baseId,id,"Chords",published.publicationRevision)).identity.playbackSha256).toBe(saved.identity.playbackSha256);
 expect((await ownerReviewList()).entries[0]!.variants[0]!.decisions.find(d=>d.mode==="Chords")?.status).toBe("accepted");
 expect((await readMusicalReviews(baseId))[0]!.receipt.publicationRevision).toBe(revision);
 await expect(saveHarmonyCandidate(request)).rejects.toThrow(/publication changed/);
 // A failed catalog commit must retain the exact installed candidate and recovery journal.
 const nextRevision=published.publicationRevision;
 const nextEvents=[{kind:"chord",beat:0,durationBeats:8,name:"G"}];
 const nextPreview=buildHarmonyCandidate(data,{id,baseId,title:row.title,artist:row.artist,revision:nextRevision},nextEvents);
 const nextSaved=await saveHarmonyCandidate({id,revision:nextRevision,sourceFingerprint:data.sourceFingerprint!,events:nextEvents,previewDigest:nextPreview.digest,previewPlaybackSha256:nextPreview.playbackSha256});
 const nextReview=await importHarmonyReview(id,nextRevision,nextSaved.candidateSha256,{...review,...nextSaved.identity,coverage:[{startBeat:0,endBeat:nextSaved.endBeat}]});
 const nextAuthorization={...authorize,revision:nextRevision,candidateSha256:nextSaved.candidateSha256,receiptSha256s:[nextReview.receiptSha256]};
 getDb().exec("CREATE TRIGGER fail_harmony_commit BEFORE INSERT ON songs WHEN NEW.base_id='harmony-fixture' BEGIN SELECT RAISE(ABORT,'injected commit failure'); END;");
 await expect(publishHarmonyCandidate(nextAuthorization)).rejects.toThrow(/reconcil/i);
 const recovery=(await catalogRecoveryInventory()).entries.find(entry=>entry.baseId===baseId)!;
 expect(recovery).toMatchObject({operation:"publish",state:"reviewable",installed:true,rollback:true});
 expect(await Promise.all(paths.map(path=>readFile(path)))).toEqual(before);
 getDb().exec("DROP TRIGGER fail_harmony_commit");
 for(const name of ["chord-timeline.json",".musical-review-binding.json"]){
  const sidecar=join(root,"artifacts",baseId,name),intact=await readFile(sidecar);
  await writeFile(sidecar,Buffer.concat([intact,Buffer.from("damaged")]));
  await expect(recoverCatalogPublication(baseId,recovery.journalSha256!)).rejects.toThrow(/harmony|hash|publication/i);
  expect((await catalogRecoveryInventory()).entries[0]).toMatchObject({installed:true,rollback:true});
  await writeFile(sidecar,intact);
 }
 expect(await recoverCatalogPublication(baseId,recovery.journalSha256!)).not.toBeNull();
 expect((await catalogRecoveryInventory()).entries).toHaveLength(0);
 const recoveredRevision=(await withStablePublication(baseId,undefined,async()=>null)).publicationRevision!;
 expect(recoveredRevision).not.toBe(nextRevision);
 expect((await musicalOutput(baseId,id,"Chords",recoveredRevision)).identity.playbackSha256).toBe(nextSaved.identity.playbackSha256);
 expect((await ownerReviewList()).entries[0]!.variants[0]!.decisions.find(d=>d.mode==="Chords")?.status).toBe("accepted");
 expect(await Promise.all(paths.map(path=>readFile(path)))).toEqual(before);
});
