import { createHash } from 'node:crypto';
import { it,expect } from 'vitest';
import { mkdtempSync,writeFileSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { prepareCompactReviewJobs,importCompactReviewResult,parseCompactJson,validateCompactResult } from './music-review-jobs.js';
import { buildMusicReview } from './music-review.js';
import { paired,receipt } from './player-review-fixtures.js';
it('prepares one clip/claim without subprocess and excludes local paths',async()=>{const dir=mkdtempSync(join(tmpdir(),'keyspilli-jobs-test-'));try{const c=paired(),report=buildMusicReview({clips:[{id:c.id,audio:{...c.output,durationSeconds:1.2,derivativeSha256:null},eventsSha256:null,analyzerSha256:null,pairedCapture:c,pairedCaptureSha256:receipt().captureSha256,playerInput:receipt()}]});const jobs=await prepareCompactReviewJobs(report,join(dir,'jobs'));expect(jobs).toHaveLength(1);expect(jobs[0]!.status).toBe('prepared');expect(JSON.stringify(jobs[0]!.evidence)).not.toContain('/fixture');expect(jobs[0]!.evidence.claims[0]!.origin).toBe('model-estimate');}finally{rmSync(dir,{recursive:true,force:true});}});
it('strict compact validation rejects false approval, foreign claims and long text',()=>{const evidence={schemaVersion:1 as const,kind:'anti-music-evidence' as const,clips:[{id:'clip',sha256:'a'.repeat(64),durationSeconds:1}],claims:[{id:'claim',clipId:'clip',startSeconds:0,endSeconds:1,text:'Untrusted claim',origin:'unknown' as const,uncertainty:'unknown'}],context:{sourceAuthority:'unknown' as const,allowedDifferences:[]},limitations:['unqualified']};const r={schemaVersion:1,kind:'anti-music-review',comparisonStatus:'uncertain',findings:[{clipId:'clip',claimIds:['claim'],startSeconds:0,endSeconds:1,description:'Inspect',origin:'model-advisory',uncertainty:'unknown'}],limitations:['not heard'],musicalAcceptance:'not-established'};expect(validateCompactResult(r,evidence)).toEqual(r);expect(()=>validateCompactResult({...r,musicalAcceptance:'approved'},evidence)).toThrow();expect(()=>validateCompactResult({...r,findings:[{...r.findings[0],claimIds:['foreign']}]},evidence)).toThrow();expect(()=>validateCompactResult({...r,findings:[{...r.findings[0],description:'x'.repeat(501)}]},evidence)).toThrow();});

it('imports only a pinned configuration and preserves neighboring prepared jobs',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'keyspilli-import-test-'));try{
 const sha=(b:Buffer|string)=>createHash('sha256').update(b).digest('hex'),wav=Buffer.alloc(44+88200);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(44100,24);wav.writeUInt32LE(88200,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(88200,40);
 const path=join(dir,'clip.wav'),helper=join(dir,'anti.py'),schema=join(dir,'schema.json');writeFileSync(path,wav);writeFileSync(helper,'fixture');writeFileSync(schema,'{}');
 const report=buildMusicReview({clips:[{id:'clip',audio:{path,sha256:sha(wav),sampleRate:44100,channels:1,frames:44100,durationSeconds:1,derivativeSha256:null},eventsSha256:null,analyzerSha256:null,renderer:{schemaVersion:1,kind:'keyspilli-renderer-verification',status:'ok',audioSha256:sha(wav),templateBankSha256:'f'.repeat(64),origin:'renderer-informed',unexpectedPitches:[60,61],missingExpectedPitches:[],matchedPitches:[],limitations:['fixture']}}]});
 const accountBinding={gatewayInstance:'a'.repeat(32),configSha256:'b'.repeat(64)};
 const config={helperPath:helper,helperSha256:sha('fixture'),responseSchemaPath:schema,responseSchemaSha256:sha('{}'),model:'gemini-3.1-pro',gateway:'http://127.0.0.1:51122/v1',maxOutputTokens:2048 as const,timeoutSeconds:90 as const,accountBinding};
 const jobs=await prepareCompactReviewJobs(report,join(dir,'jobs'),config),job=jobs[0]!,review={schemaVersion:1,kind:'anti-music-review',comparisonStatus:'uncertain',findings:[],limitations:['No listening'],musicalAcceptance:'not-established'};
 const raw={mode:'review-music',model:config.model,gateway:config.gateway,runStatus:'success',output_text:JSON.stringify(review),metadata:{music_evidence_sha256:job.evidenceSha256,music_review_profile:'compact-v1',retry_disposition:'disabled',consult_attempts:[{}],result_quality:'complete',music_review:review,account_binding_gateway_instance:accountBinding.gatewayInstance,account_binding_config_sha256:accountBinding.configSha256,music_request_configuration:{maxOutputTokens:2048,timeoutSeconds:90,helperSha256:config.helperSha256,responseSchemaSha256:config.responseSchemaSha256}}};
 const result=join(dir,'result.json');writeFileSync(result,JSON.stringify({...raw,model:'foreign'}));await expect(importCompactReviewResult(job,result)).rejects.toThrow(/foreign/);writeFileSync(result,JSON.stringify(raw));expect((await importCompactReviewResult(job,result)).status).toBe('completed');expect(jobs[1]!.status).toBe('prepared');
 const second=jobs[1]!;
 writeFileSync(result,JSON.stringify({...raw,metadata:{...raw.metadata,music_evidence_sha256:second.evidenceSha256,account_binding_config_sha256:'c'.repeat(64)}}));
 await expect(importCompactReviewResult(second,result)).rejects.toThrow(/binding/);
 writeFileSync(result,JSON.stringify({...raw,runStatus:'partial',metadata:{...raw.metadata,music_evidence_sha256:second.evidenceSha256,result_quality:'incomplete'}}));expect((await importCompactReviewResult(second,result)).status).toBe('partial');
 }finally{rmSync(dir,{recursive:true,force:true});}
});

it('rejects duplicate escaped JSON keys and nonfinite numeric values',()=>{expect(()=>parseCompactJson('{"a":1,"\\u0061":2}')).toThrow(/duplicate/);expect(()=>parseCompactJson('{"a":1e999}')).toThrow(/nonfinite/);expect(parseCompactJson('{"a":[{"a":1}]}')).toEqual({a:[{a:1}]});});
