import {afterAll,expect,it} from "vitest";
import {mkdtempSync} from "node:fs";
import {readFile,writeFile,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {getDb,getSong,ingestSource} from "@keyspilli/catalog";
import {importMusicalReview,musicalOutput,readMusicalReviews} from "./owner-admission";
import {withStablePublication} from "./catalog-api";
const old=process.env.KEYSPILLI_DATA_DIR,root=mkdtempSync(join(tmpdir(),"keyspilli-admission-"));process.env.KEYSPILLI_DATA_DIR=root;
afterAll(async()=>{getDb().close();if(old===undefined)delete process.env.KEYSPILLI_DATA_DIR;else process.env.KEYSPILLI_DATA_DIR=old;await rm(root,{recursive:true,force:true});});
it("imports exact human attestations atomically and idempotently without changing music or exclusions",async()=>{
 await writeFile(join(root,"manifest.json"),JSON.stringify({songs:[]}));
 const buf=Buffer.from(`<score-partwise><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1"><measure number="1"><attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes>${['C','D','E','F','G','A','B','C'].map(step=>`<note><pitch><step>${step}</step><octave>4</octave></pitch><duration>1</duration></note>`).join('')}</measure></part></score-partwise>`);
 expect((await ingestSource({baseId:"review-fixture",buf,title:"Review fixture",artist:"Authored",category:"Test",contentType:"standard"})).error).toBeUndefined();
 await writeFile(join(root,"learner-review.json"),JSON.stringify({verdicts:{"review-fixture":{blocked:true}}}));
 const revision=(await withStablePublication("review-fixture",undefined,async()=>null)).publicationRevision!;
 const output=await musicalOutput("review-fixture","review-fixture-a","Original",revision);
 const path=join(root,"artifacts/review-fixture/a/notes.json"),before=await readFile(path);
 const evidence=[{id:"synthetic-test-attestation",sha256:"c".repeat(64)}];
 const receipt={schemaVersion:1,kind:"musical-review-receipt",...output.identity,reviewer:{id:"fixture-owner",role:"owner",independent:false},reviewedAt:"2026-10-03T11:00:00Z",coverage:[{startBeat:0,endBeat:2}],decision:"accepted",rationale:"Synthetic fixture tests transport; no real musical acceptance.",checks:{source:{result:"passed",evidence},listening:{result:"passed",evidence},keyboard:{result:"pending",evidence:[]}}};
 const imported=await importMusicalReview(receipt);expect(imported.summary.status).toBe("partial");
 expect((await importMusicalReview(receipt)).receiptSha256).toBe(imported.receiptSha256);
 expect(await readMusicalReviews("review-fixture")).toHaveLength(1);
 expect(await readFile(path)).toEqual(before);expect(getSong("review-fixture-a")).toBeUndefined();
 await expect(importMusicalReview({...receipt,playbackSha256:"0".repeat(64)})).rejects.toThrow(/identity/);
 await expect(importMusicalReview({...receipt,coverage:[{startBeat:0,endBeat:output.endBeat+1}]})).rejects.toThrow(/coverage/);
 await writeFile(join(root,"artifacts/review-fixture/.publication-id"),"new-version");
 await expect(importMusicalReview(receipt)).rejects.toThrow(/publication changed/);
 expect(await readMusicalReviews("review-fixture")).toHaveLength(1);
 await writeFile(join(root,"artifacts/.review-fixture.reconciliation.json"),"{}");
 await expect(importMusicalReview({...receipt,publicationRevision:"new-version"})).rejects.toThrow(/publication changed/);
});
