import { expect,it } from 'vitest';
import { mkdtempSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { savePlayerCapture, type PlayerCapture } from '../../e2e/player-audio-capture';
const sha=(b:Buffer)=>createHash('sha256').update(b).digest('hex');
function wav(float=false,ch=float?2:1){const width=float?4:2,b=Buffer.alloc(44+128*ch*width);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(float?3:1,20);b.writeUInt16LE(ch,22);b.writeUInt32LE(44100,24);b.writeUInt32LE(44100*width*ch,28);b.writeUInt16LE(width*ch,32);b.writeUInt16LE(width*8,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);if(float)b.writeFloatLE(1.5,44);return b;}
function capture():PlayerCapture{const b=wav(),f=wav(true);return {wav:b,sha256:sha(b),durationSeconds:128/44100,sampleRate:44100,firstSampleContextSeconds:2,recorderClock:'audio-worklet-frame',sourceClockOffsetSeconds:0,sourceClockOffsetsSeconds:{},rms:.1,peak:1,samplerStarts:[],sampleAssets:[{url:'https://fixture.invalid/sample',sha256:'a'.repeat(64),bytes:1024}],beforeCompressor:{wav:f,sha256:sha(f),forwardWav:wav(true,1),forwardSha256:sha(wav(true,1)),sampleRate:44100,frames:128,channels:2,encoding:'float32-le',firstSampleContextSeconds:2,rms:.1,peak:1.5,compressor:{threshold:-24,knee:12,ratio:3,attack:.005,release:.15}}};}
const renderer={moduleVersion:'1.0.0',moduleSha256:'a'.repeat(64),browserVersion:'151.0'};
it('saves paired manifest and Float32 headroom only on explicit request',()=>{const dir=mkdtempSync(join(tmpdir(),'keyspilli-contract-'));try{const path=join(dir,'out.wav'),manifestPath=join(dir,'paired.json');savePlayerCapture(path,capture(),{id:'test',renderer,manifestPath});const manifest=JSON.parse(readFileSync(manifestPath,'utf8'));expect(manifest.input.encoding).toBe('pcm-f32le');expect(readFileSync(manifest.input.path).readFloatLE(44)).toBe(1.5);expect(manifest.firstSampleContextSeconds).toBe(2);expect(manifest.output.frames).toBe(128);}finally{rmSync(dir,{recursive:true,force:true});}});
it('retains legacy mono file without sidecar and refuses bad clock before write',()=>{const dir=mkdtempSync(join(tmpdir(),'keyspilli-contract-'));try{const path=join(dir,'out.wav');savePlayerCapture(path,capture());expect(readFileSync(path).readUInt16LE(22)).toBe(1);expect(existsSync(join(dir,'out-before-compressor.wav'))).toBe(false);const bad=capture();bad.beforeCompressor!.firstSampleContextSeconds=3;const next=join(dir,'bad.wav');expect(()=>savePlayerCapture(next,bad,{id:'bad',renderer,manifestPath:join(dir,'bad.json')})).toThrow(/clock/);expect(existsSync(next)).toBe(false);}finally{rmSync(dir,{recursive:true,force:true});}});
